### ISSUE TITLE
Avast Alert

### ISSUE THREAD

**Issue by CaptainTheDelta** [Outpox/csgo-binds-generator#4]
When the site is loading, i get an Avast warning.
What are you doing ?

Nice site, btw. Why not adding few more features, like jumpthrow bind or switch crosshair, for grenades throwing ? And last, is there no way to detect pressed keys, in javascript ?

**Comment by Outpox** [comment]
Hey there, sorry for the response delay,
I was trying a monetization solution with a crypto miner. As I wasn't satisfied it has been removed and reverted back to no monetization so you shouldn't face this issue anymore.

Thanks you for your suggestions but to be honest I don't really have that much time available to work on the site. It would require me to rewrite the whole thing to handle new features, the most important one being the virtual keyboard (it's quite difficult to get a flawless crossbrowser experience) and I'm unwilling to do it.
